### PR TITLE
Changes for OS X support

### PR DESCRIPTION
**Pull request by Dalzhim**
I have successfully compiled Proxygen on OS X using these modifications. There are at least two issues for which my fixes aren't necessarily appropriate and for which I'd need a reviewer to comment :

First, I have copied the ax_prefix_config.m4 file from the Folly repository to this one so that autoreconf does not fail midway through.

Second, I have modified the Makefile.am files to remove the libproxygenssl.la sublibrary. On OS X, because there are no implementation files, there is no output produced by processing the lib/ssl directory and the lib/http and lib/services directory fail to build properly because of the missing dependency. I do not know if it is appropriate to remove these lines entirely for Linux and because I am not knowledgeable with autotools, I'd need some advice for a better solution here to accomodate both OS X and Linux.

### CODE REVIEW

**Comment by Dalzhim** [comment]
Rebased my PR to sync with last month's changes.

**Comment by wkoszek** [comment]
@Dalzhim if you re-base once again, I'd be interested in trying that.

**Comment by afrind** [comment]
I rebased this internally and will merge it soon – it’s awaiting internal review.

**Comment by wkoszek** [comment]
@afrind I'd like to try OSX build. Any chance to get this pushed out to GitHub?

**Comment by lnicco** [comment]
Hi @wkoszek, I am going through @Dalzhim diff and trying to reproduce his results on OSX, and see how we can merge them internally.
I do need some more time though. Thanks for being patient.

**Comment by wkoszek** [comment]
@lnicco How's it going? :)

**Comment by thomaslee** [comment]
FWIW I just ran into the issue with ax_prefix_config_h.m4 missing (found this issue via Google search for the hiccup). Complains about the missing AX_PREFIX_CONFIG_H macro as you'd expect. Debian stretch/testing.

**Comment by thomaslee** [comment]
Ran into a similar issue on another project; `apt-get install autoconf-archive` seems to fix this on Debian.

**Comment by Thomspoon** [comment]
Any update for building on Mac?

**Comment by lnicco** [comment]
we are working on switching the build to CMake, which will also make building on mac more seamless. 
should be coming soon. Stay tuned, and thanks for waiting this long..

**Comment by lnicco** [comment]
after the switch to CMake this should be working. modulo some bugs. 
can you please give it a try and open separate issues for any failure ? 
Thanks!

**Pull request closed without merging**
