### PR TITLE
Added WebSocket support

### PR DESCRIPTION
**Pull request by kekekeks**
I'm not sure that my design is correct, but at least I haven't touched anything else to implement this.

Tested with Firefox and Chrome.

### CODE REVIEW

**Comment by bugok** [comment]
@kekekeks can you please add a test case in proxygen/httpserver/tests?

**Comment by kekekeks** [comment]
I've used actual browsers for testing, so I don't know how to make automated tests for this. Writing own websocket client implementation seems to be error-prone. Is there any way to use html page with js for unit testing? Or I have to use some 3rd-party websocket client library?

**Comment by bugok** [comment]
To be frank, I'm not very familiar with websockets. However, it seems to be more complex than your given implementation. For example, see this project: https://github.com/zaphoyd/websocketpp.
I wouldn't want to include a partial implementation. 
@kekekeks what do you think?

**Comment by kekekeks** [comment]
Most needed features (i. e. network layer, HTTP Upgrade, TLS) are already supported by proxygen, https://github.com/zaphoyd/websocketpp - that guy has created a whole HTTP stack and also ignored the presence of openssl. He also has support for outdated draft specs while I've only implemented final protocol version from  [RFC](https://tools.ietf.org/html/rfc6455). 

Implementation, however, has some limitations:
- No masking in server frames (it's not required by RFC, but is a nice thing to have).
- There is also no built-in support for some control frames like PING/CLOSE (implementation does not send them automagically, user code should do it itself. It responses to PING frames from client as RFC requires however.
- There is no way to abort connection if client frame is too large (user code doesn't know about the frame until it's received). The best idea I have about it is to split one physical frame to virtual ones. It should not cause any problems since browsers can set any frame size and it's not controlled by user code.

But these limitations does not mean that implementation is incomplete.

**Comment by bugok** [comment]
@kekekeks we would like to get this in.
I'll get this in for review, but I would request you to come up with tests. 
Thanks.

**Comment by bugok** [comment]
I'm closing this for now. Feel free to open / create a new one if you'd like to make changes and add unit tests.

**Pull request closed without merging**
