### PR TITLE
For Travis just build Docker image.

### PR DESCRIPTION
**Pull request by wkoszek**
Instead of removing Travis whatsoever, we could use the Travis to just build the Docker container, since it proves that the code is compiling fine.

However there's one problem: the build takes too long on free Travis, so I have a hard time validating this pull request. It timed out.

https://travis-ci.org/wkoszek/proxygen/builds/140990904

Does Facebook have a commercial Travis account? Would you be willing to accept the pull request and start building `proxygen` again?

### CODE REVIEW

**Comment by wkoszek** [comment]
@afrind Any chance to get this merged? We either merge or I will close it.

**Comment by russoue** [comment]
@wkoszek, I will be working on it this week. I will update the issue as soon as possible.

**Comment by wkoszek** [comment]
@russoue No pressure. Was just asking. Would be very convenient to have OSX support to try proxygen out.

**Comment by wkoszek** [comment]
@russoue Do you think you could enable Travis at https://travis-ci.org/facebook/proxygen/builds ?

**Comment by russoue** [comment]
@wkoszek, I found that I don't have the privilege to do it. I will find who has it and request him to enable it.

**Comment by russoue** [comment]
@afrind, can you try enabling Travis CI build for `proxygen`? I don't have the admin privileges to do it.

**Comment by russoue** [comment]
Thanks @sdwilsh for enabling it.

**Comment by wkoszek** [comment]
@sdwilsh @russoue Doesn't seem like we're triggering Travis Ci correctly:

https://travis-ci.org/facebook/proxygen

**Comment by sdwilsh** [comment]
@wkoszek - I've been on leave.  Is it working correctly now?

**Comment by wkoszek** [comment]
@sdwilsh No. Take a look at https://travis-ci.org/facebook/proxygen When somebody pushes a commit to proxygen now, it should build. There've been commits to the repo since we enabled that, but build wasn't triggered. If you have an account on Travis-Ci for FB, you can force a build by pressing this 'restart' circle:

image

**Comment by sdwilsh** [comment]
I think I've fixed this now.  Builds for pushes was turned off.

**Comment by wkoszek** [comment]
@sdwilsh Can you trigger a build as an experiment?

**Comment by sdwilsh** [comment]
I didn't see a way to do so in the UI without pushing a commit.  I could retry the build from a year ago, but that's going to do it off of that revision AFAIK.

**Comment by wkoszek** [comment]
@sdwilsh Can you make a dummy commit?

**Comment by sdwilsh** [comment]
Honestly, I don't have the bandwidth for that right now.  I'd expect a commit to come in soon and we'll see if it works (I expect it to).

**Pull request closed without merging**
