### PR TITLE
Cleanup Dockerfile: Use less commands.

### PR DESCRIPTION
**Pull request by wkoszek**
Tested by performing a build with `docker build .`. Worked fine. Included `sudo` already, which is a part of the separate pull request.

### CODE REVIEW

**Comment by wkoszek** [comment]
@afrind Pre-merged with latest `master`.

**Comment by wkoszek** [comment]
@afrind Any chance to get this merged? We either merge or close it.

**Comment by afrind** [comment]
Hey sorry about that. I didn’t actually have a docker setup to test with until last week.  Someone else is oncall for libproxygen now, I will hand the merge off to them and it should happen this week.

**Comment by russoue** [comment]
@wkoszek, after the latest change has been pushed in Dockerfile there is a conflict now. Can you please resolve it and update the PR?

**Comment by wkoszek** [comment]
@russoue Try now.

**Pull request closed without merging**
